export { default as ManageMenuItemsPage } from "./MenuItems"
export { default as TablesPage } from "./Tables"
export { default as ManageReservationsPage } from "./Reservations"
export { default as ManageOrdersPage } from "./Orders"
export { default as ChatPage } from "./ChatPage"