export { default as ManageFoodCategoriesPage } from "./ManageFoodCategories"
export { default as ManageRestaurantManagersPage } from "./ManageUsers/ManageRestaurantManagers"
export { default as ManageCustomersPage } from "./ManageUsers/ManageCustomers"
export { default as ManageRestaurantsPage } from "./ManageRestaurants/"
export { default as ManageReservationsPage } from "./ManageReservations/"
export { default as ManageOrdersPage } from "./ManageOrders/"